SetCVar("Sound_SFXVolume", 0.7)
SetCVar("Sound_MusicVolume", 0.5)
SetCVar("Sound_AmbienceVolume", 1)
SetCVar("Sound_DialogVolume", 1)
SetCVar("scriptErrors", 1)
SetCVar("alwaysCompareItems", 1)
SetCVar("cameraDistanceMaxZoomFactor", 2.6)
SetCVar("floatingCombatTextFloatMode", 3)
SetCVar("floatingCombatTextCombatHealing", 0)
SetCVar("floatingCombatTextReactives", 0)
SetCVar("floatingCombatTextCombatState", 1)
SetCVar("taintLog", 1)
SetCVar("rawMouseEnable", 1)
SetCVar("ffxDeath", 0)
SetCVar("lockActionBars", 0)
SetCVar("enableFloatingCombatText", 1)
SetCVar("nameplateMaxDistance", 40)

hooksecurefunc(StaticPopupDialogs["DELETE_GOOD_ITEM"], "OnShow", function(self)
    self.editBox:SetText(DELETE_ITEM_CONFIRM_STRING)
end)

CompactUnitFrameProfilesGeneralOptionsFrameWidthSlider:SetMinMaxValues(137, 137)
CompactUnitFrameProfilesGeneralOptionsFrameHeightSlider:SetMinMaxValues(54, 54)